attribute:
  '@PhysicalName': cr07c_ApplicationDeadline
  Type: date
  Name: cr07c_applicationdeadline
  LogicalName: cr07c_applicationdeadline
  RequiredLevel: required
  DisplayMask: ValidForForm|ValidForGrid
  ImeMode: auto
  ValidForUpdateApi: 1
  ValidForReadApi: 1
  ValidForCreateApi: 1
  IsCustomField: 1
  IsAuditEnabled: 1
  IsSecured: 0
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  IsRenameable: 1
  CanModifySearchSettings: 1
  CanModifyRequirementLevelSettings: 1
  CanModifyAdditionalSettings: 1
  SourceType: 0
  IsGlobalFilterEnabled: 0
  IsSortableEnabled: 0
  CanModifyGlobalFilterSettings: 1
