# Relationship: LCI Grant Application to LCI Grant Program
entityrelationship:
  RelationshipType: ManyToOne
  ReferencingEntity: cr07c_lcigrantapplication
  ReferencingAttribute: cr07c_grantprogramid
  ReferencedEntity: cr07c_lcigrantprogram
  ReferencedAttribute: cr07c_programid
  SchemaName: cr07c_lcigrantapplication_cr07c_lcigrantprogram
  displaynames:
    displayname:
      '@description': Linked Grant Program
      '@languagecode': 1033
  Descriptions:
    Description:
      '@description': Links LCI Grant Application to LCI Grant Program
      '@languagecode': 1033
