Workflow:
  '@WorkflowId': '{1358e769-f077-44dc-b271-83bc9bf361a6}'
  '@Name': Contact
  '@Description': Client specific operational procedures for Contact
  XamlFileName: /portablebusinesslogics/1358e769-f077-44dc-b271-83bc9bf361a6/Contact-1358E769-F077-44DC-B271-83BC9BF361A6.xaml
  Type: 1
  Subprocess: 0
  Category: 2
  Mode: 1
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ProcessTriggerScope: 2
  ModernFlowType: 0
  PrimaryEntity: cr07c_Contact2
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': Contact
  Descriptions:
    Description:
      '@languagecode': 1033
      '@description': Client specific operational procedures for Contact
