Workflow:
  '@WorkflowId': '{c511e1e6-5941-f011-b4cb-002248222778}'
  '@Name': Case
  '@Description': Click to add description
  XamlFileName: /portablebusinesslogics/c511e1e6-5941-f011-b4cb-002248222778/Case-C511E1E6-5941-F011-B4CB-002248222778.xaml
  Type: 1
  Subprocess: 0
  Category: 2
  Mode: 1
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ProcessTriggerScope: 2
  ModernFlowType: 0
  PrimaryEntity: cr07c_Case2
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': Case
  Descriptions:
    Description:
      '@languagecode': 1033
      '@description': Click to add description
