Workflow:
  '@WorkflowId': '{44d2728b-7680-480e-bade-7e5467edf783}'
  '@Name': Organization
  '@Description': Client specific operational procedures for Organization
  XamlFileName: /portablebusinesslogics/44d2728b-7680-480e-bade-7e5467edf783/Organization-44D2728B-7680-480E-BADE-7E5467EDF783.xaml
  Type: 1
  Subprocess: 0
  Category: 2
  Mode: 1
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ProcessTriggerScope: 2
  ModernFlowType: 0
  PrimaryEntity: cr07c_Organization
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': Organization
  Descriptions:
    Description:
      '@languagecode': 1033
      '@description': Client specific operational procedures for Organization
