Workflow:
  '@WorkflowId': '{c2d3e4f5-2222-3333-4444-555566667777}'
  '@Name': User Operational Procedures
  '@Description': Client specific operational procedures for User Management
  XamlFileName: /portablebusinesslogics/c2d3e4f5-2222-3333-4444-555566667777/User-C2D3E4F5-2222-3333-4444-555566667777.xaml
  Type: 1
  Subprocess: 0
  Category: 2
  Mode: 1
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ProcessTriggerScope: 2
  ModernFlowType: 0
  PrimaryEntity: cr07c_User2
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': User Operational Procedures
  Descriptions:
    Description:
      '@languagecode': 1033
      '@description': Client specific operational procedures for User Management
