attribute:
  '@PhysicalName': cr07c_ApplicationDeadline
  Type: datetime
  Name: cr07c_applicationdeadline
  LogicalName: cr07c_applicationdeadline
  RequiredLevel: none
  DisplayMask: ValidForAdvancedFind|ValidForForm|ValidForGrid
  ImeMode: auto
  ValidForUpdateApi: 1
  ValidForReadApi: 1
  ValidForCreateApi: 1
  IsCustomField: 1
  IsAuditEnabled: 1
  IsSecured: 0
  IntroducedVersion: 1.0
  IsCustomizable: 1
  IsRenameable: 1
  CanModifySearchSettings: 1
  CanModifyRequirementLevelSettings: 1
  CanModifyAdditionalSettings: 1
  SourceType: 0
  IsGlobalFilterEnabled: 0
  IsSortableEnabled: 0
  CanModifyGlobalFilterSettings: 1
  CanModifyIsSortableSettings: 1
  IsDataSourceSecret: 0
  AutoNumberFormat: ''
  IsSearchable: 0
  IsFilterable: 1
  IsRetrievable: 1
  IsLocalizable: 0
  Format: date
  Behavior: 3
  displaynames:
    displayname:
      '@description': Application Deadline
      '@languagecode': 1033
  Descriptions:
    Description:
      '@description': Deadline for grant applications submission
      '@languagecode': 1033
