Workflow:
  '@WorkflowId': '{84e1c7a5-3d42-f011-b4cb-002248222778}'
  '@Name': Primary Contact
  JsonFileName: /modernflows/84e1c7a5-3d42-f011-b4cb-002248222778/PrimaryContact-84E1C7A5-3D42-F011-B4CB-002248222778.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': Primary Contact
