---
$schema: https://developer.microsoft.com/json-schemas/cds/2019-04/manifest
guid: '{85F44B8D-0F3E-4C7A-8B2D-9E1A5B4C7D6E}'
type: picklist
logicalname: cr07c_applicationstatus
displayname: Application Status
description: Current status of the LCI grant application
displaynames:
  1033: Application Status
descriptions:
  1033: Current status of the LCI grant application
optionset:
  isGlobal: false
  options:
    100000000:
      label: Draft
      descriptions:
        1033: Application is being prepared
      color: '#F0F8FF'
    100000001:
      label: Submitted
      descriptions:
        1033: Application has been submitted for review
      color: '#87CEEB'
    100000002:
      label: In Review
      descriptions:
        1033: Application is currently under review
      color: '#FFD700'
    100000003:
      label: Approved
      descriptions:
        1033: Application has been approved for funding
      color: '#90EE90'
    100000004:
      label: Denied
      descriptions:
        1033: Application has been denied funding
      color: '#FFB6C1'
requirementlevel: Required
