attribute:
  '@PhysicalName': cr07c_LCIGrantApplicationId
  Type: primarykey
  Name: cr07c_lcigrantapplicationid
  LogicalName: cr07c_lcigrantapplicationid
  RequiredLevel: systemrequired
  DisplayMask: ValidForAdvancedFind|RequiredForGrid
  ImeMode: auto
  ValidForUpdateApi: 0
  ValidForReadApi: 1
  ValidForCreateApi: 1
  IsCustomField: 0
  IsAuditEnabled: 0
  IsSecured: 0
  IntroducedVersion: 1.0.0.0
  SourceType: 0
  IsGlobalFilterEnabled: 0
  IsSortableEnabled: 0
  IsDataSourceSecret: 0
  AutoNumberFormat: ''
  IsSearchable: 0
  IsFilterable: 1
  IsRetrievable: 1
  IsLocalizable: 0
  displaynames:
    displayname:
      '@description': LCI Grant Application
      '@languagecode': 1033
  Descriptions:
    Description:
      '@description': Unique identifier for entity instances
      '@languagecode': 1033
