attribute:
  '@PhysicalName': cr07c_ApplicationId
  Type: nvarchar
  Name: cr07c_applicationid
  LogicalName: cr07c_applicationid
  RequiredLevel: required
  DisplayMask: PrimaryName|ValidForAdvancedFind|ValidForForm|ValidForGrid|RequiredForForm
  ImeMode: auto
  ValidForUpdateApi: 1
  ValidForReadApi: 1
  ValidForCreateApi: 1
  IsCustomField: 1
  IsAuditEnabled: 1
  IsSecured: 0
  IntroducedVersion: 1.0
  IsCustomizable: 1
  IsRenameable: 1
  CanModifySearchSettings: 1
  CanModifyRequirementLevelSettings: 1
  CanModifyAdditionalSettings: 1
  SourceType: 0
  IsGlobalFilterEnabled: 0
  IsSortableEnabled: 0
  CanModifyGlobalFilterSettings: 1
  CanModifyIsSortableSettings: 1
  IsDataSourceSecret: 0
  IsSearchable: 1
  IsFilterable: 0
  IsRetrievable: 1
  IsLocalizable: 0
  Format: text
  MaxLength: 50
  Length: 100
  displaynames:
    displayname:
      '@description': Application ID
      '@languagecode': 1033
  Descriptions:
    Description:
      '@description': Primary Name for LCI Grant Application
      '@languagecode': 1033
