attribute:
  '@PhysicalName': cr07c_ApplicationStatus
  Type: picklist
  Name: cr07c_applicationstatus
  LogicalName: cr07c_applicationstatus
  RequiredLevel: required
  DisplayMask: ValidForForm|ValidForGrid
  ImeMode: auto
  ValidForUpdateApi: 1
  ValidForReadApi: 1
  ValidForCreateApi: 1
  IsCustomField: 1
  IsAuditEnabled: 1
  IsSecured: 0
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  IsRenameable: 1
  CanModifySearchSettings: 1
  CanModifyRequirementLevelSettings: 1
  CanModifyAdditionalSettings: 1
  SourceType: 0
  IsGlobalFilterEnabled: 0
  IsSortableEnabled: 0
  CanModifyGlobalFilterSettings: 1
  CanModifyIsSortableSettings: 1
  IsDataSourceSecret: 0
  IsSearchable: 0
  IsFilterable: 0
  IsRetrievable: 0
  IsLocalizable: 0
  optionset:
    '@Name': cr07c_lcigrantapplication_cr07c_applicationstatus
    OptionSetType: picklist
    IntroducedVersion: 1.0.0.0
    IsCustomizable: 1
    displaynames:
      displayname:
        '@description': cr07c_lcigrantapplication_cr07c_applicationstatus
        '@languagecode': 1033
    options:
      option:
      - '@value': 100000000
        '@IsHidden': 0
        labels:
          label:
            '@description': Draft
            '@languagecode': 1033
      - '@value': 100000001
        '@IsHidden': 0
        labels:
          label:
            '@description': Submitted
            '@languagecode': 1033
      - '@value': 100000002
        '@IsHidden': 0
        labels:
          label:
            '@description': In Review
            '@languagecode': 1033
      - '@value': 100000003
        '@IsHidden': 0
        labels:
          label:
            '@description': Approved
            '@languagecode': 1033
      - '@value': 100000004
        '@IsHidden': 0
        labels:
          label:
            '@description': Denied
            '@languagecode': 1033
  displaynames:
    displayname:
      '@description': Application Status
      '@languagecode': 1033
  Descriptions:
    Description:
      '@description': Status of the grant application
      '@languagecode': 1033
