attribute:
  '@PhysicalName': cr07c_LCIGrantApplicationId
  Type: primarykey
  Name: cr07c_lcigrantapplicationid
  LogicalName: cr07c_lcigrantapplicationid
  RequiredLevel: systemrequired
  DisplayMask: ValidForAdvancedFind|RequiredForGrid
  ImeMode: auto
  ValidForUpdateApi: 0
  ValidForReadApi: 1
  ValidForCreateApi: 1
  IsCustomField: 1
  IsAuditEnabled: 0
  IsSecured: 0
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  IsRenameable: 1
  CanModifySearchSettings: 1
  CanModifyRequirementLevelSettings: 0
  CanModifyAdditionalSettings: 1
  SourceType: 0
  IsGlobalFilterEnabled: 0
  IsSortableEnabled: 0
  CanModifyGlobalFilterSettings: 1
