attribute:
  '@PhysicalName': cr07c_ApplicationStatus
  Type: picklist
  Name: cr07c_applicationstatus
  LogicalName: cr07c_applicationstatus
  RequiredLevel: required
  DisplayMask: ValidForAdvancedFind|ValidForForm|ValidForGrid|RequiredForForm
  ImeMode: auto
  ValidForUpdateApi: 1
  ValidForReadApi: 1
  ValidForCreateApi: 1
  IsCustomField: 1
  IsAuditEnabled: 1
  IsSecured: 0
  IntroducedVersion: 1.0
  IsCustomizable: 1
  IsRenameable: 1
  CanModifySearchSettings: 1
  CanModifyRequirementLevelSettings: 1
  CanModifyAdditionalSettings: 1
  SourceType: 0
  IsGlobalFilterEnabled: 0
  IsSortableEnabled: 0
  CanModifyGlobalFilterSettings: 1
  CanModifyIsSortableSettings: 1
  IsDataSourceSecret: 0
  IsSearchable: 1
  IsFilterable: 0
  IsRetrievable: 1
  IsLocalizable: 0
  OptionSet:
    Option:
      - '@value': 1
        '@description': Draft
      - '@value': 2
        '@description': Submitted
      - '@value': 3
        '@description': In Review
      - '@value': 4
        '@description': Approved
      - '@value': 5
        '@description': Denied
  displaynames:
    displayname:
      '@description': Application Status
      '@languagecode': 1033
  Descriptions:
    Description:
      '@description': Status of the application
      '@languagecode': 1033
