Workflow:
  '@WorkflowId': '{d3e4f5a6-3333-4444-5555-666677778888}'
  '@Name': Organization Operational Procedures
  '@Description': Client specific operational procedures for Organization Management
  XamlFileName: /portablebusinesslogics/d3e4f5a6-3333-4444-5555-666677778888/Organization-D3E4F5A6-3333-4444-5555-666677778888.xaml
  Type: 1
  Subprocess: 0
  Category: 2
  Mode: 1
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ProcessTriggerScope: 2
  ModernFlowType: 0
  PrimaryEntity: cr07c_Organization
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': Organization Operational Procedures
  Descriptions:
    Description:
      '@languagecode': 1033
      '@description': Client specific operational procedures for Organization Management
