name: Push to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio de GitHub
      uses: actions/checkout@v3

    - name: Configurar Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Push a Azure DevOps
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        git remote add azure https://josecervantes0377:${AZURE_DEVOPS_PAT}@dev.azure.com/josecervantes0377/Pravia%20Mule%20POC/_git/Pravia%20Mule%20POC
        git push azure HEAD:main --force
